#!/usr/bin/env bash

i=1

for layers in 3 6 9; do
for cutoff in 6 8 10 12 14; do

cat << HERE > "$(printf '%02d' "${i}")_l${layers}_c${cutoff}.yaml"
# Auto generated by config/ablations/layersvscutoff/for-loopz.sh
name: proteins
tags:
  - ablation
  - layersvscutoff
  - l${layers}
  - c${cutoff}
data:
  cutoff: ${cutoff}
  sigma: 15
  separation: true
  encoding_size: 0
  encoding_base: 0
  residues: yes
  partial_entropy: no
  self_info: no
  dssp_features: no
model:
  fn: proteins.networks.ProteinGN
  layers: ${layers}
  mp_in_edges: 128
  mp_in_nodes: 512
  mp_in_globals: 512
  mp_out_edges: 16
  mp_out_nodes: 64
  mp_out_globals: 32
  dropout: 0.2
  batch_norm: false
optimizer:
  fn: torch.optim.Adam
  lr: 0.001
  weight_decay: 1.0e-05
loss:
  local_lddt:
    name: mse
    weight: 5
    balanced: false
  global_lddt:
    name: mse
    weight: 1
    balanced: false
  global_gdtts:
    name: mse
    weight: 5
    balanced: false
session:
  max_epochs: 20
  batch_size: 400
  device: cuda
  checkpoint: -1
  data:
    train:
      - data/CASP7
      - data/CASP8
      - data/CASP9
      - data/CASP10
    val:
      - data/CASP11
HERE

i=$((i+1))

done
done
