#!/usr/bin/env bash

for layers in 3 6 9; do
for cutoff in 0 6 8 10 12 14; do

cat << HERE > "l${layers}_c${cutoff}.yaml"
# Auto generated by config/ablations/layersvscutoff/for-loopz.sh
name: proteins
tags:
  - ablation
  - layersvscutoff
  - globalno
  - l${layers}
  - c${cutoff}
data:
  cutoff: ${cutoff}
  sigma: 15
  separation: true
  encoding_size: 0
  encoding_base: 0
  residues: yes
  partial_entropy: yes
  self_info: yes
  dssp_features: yes
model:
  fn: proteins.networks.ProteinGNNoGlobal
  layers: ${layers}
  mp_in_edges: 128
  mp_in_nodes: 512
  mp_out_edges: 32
  mp_out_nodes: 128
  dropout: 0.2
  batch_norm: false
optimizer:
  fn: torch.optim.Adam
  lr: 0.001
  weight_decay: 1.0e-05
loss:
  local_lddt:
    name: mse
    weight: 5
    balanced: false
  global_lddt:
    name: mse
    weight: 1
    balanced: false
  global_gdtts:
    name: mse
    weight: 5
    balanced: false
session:
  max_epochs: 30
  batch_size: 200
  device: cuda
  checkpoint: -1
  data:
    train:
      - data/CASP7
      - data/CASP8
      - data/CASP9
      - data/CASP10
    val:
      - data/CASP11
HERE

done
done
